### ISSUE TITLE
Ng-click support

### ISSUE THREAD

**Issue by tushariscoolster** [johannesjo/ng-fab-form#17]
How can we trigger validation by ng-click instead of ng-submit?

**Comment by johannesjo** [comment]
Only the validation or all the other handlers (submit-prevention, etc.) as well?

**Comment by johannesjo** [comment]
I'm closing this, as the OP is not responding and I'm not sure what would be a legitimate use-case for ng-click here.

**Comment by baskaranr** [comment]
I have the similar requirement. If we have buttons in form other then type="submit", the validation triggered on those button click also because of ng-submit.

**Comment by baskaranr** [comment]
Could anyone know how to trigger ng-form validation manually from controller method.

**Comment by johannesjo** [comment]
It's actually standard behavior (at least for chrome and ff) to submit a form when a button inside of it is clicked. To prevent this you'll have to specify the type attribute:
```
<form ng-submit="submit()">
  <button type="submit">I submit the form</button>
  <button type="button">I do something else</button>
</form>
```
