### ISSUE TITLE
Display validation messages immediately upon form load

### ISSUE THREAD

**Issue by barefootdeveloper** [johannesjo/ng-fab-form#20]
This is a question or a feature request.   Is it possible to display the validation messages immediately upon the form loading?

**Comment by johannesjo** [comment]
Well not really immediately, but you can edit the template to do so, but I assume, you want to do it conditionally?

**Comment by johannesjo** [comment]
You might be also able to set ```yourFormCtrl.$triedSubmit = true``` with the standard template. Haven't tested it yet.

**Comment by barefootdeveloper** [comment]
This is perfect and actually gets me closer to where I wanted to be.

I just set $triedSubmit to true and everything showed up.

Thanks for all your help (pull request included) and making the library.
