### ISSUE TITLE
Sourcemap file is referenced but not included in dist

### ISSUE THREAD

**Issue by barefootdeveloper** [johannesjo/ng-fab-form#21]
Super minor issue:

In the distributed js files the map file is referenced but not included so you'll get a 404 if you open developer tools while on a page that uses it.

//# sourceMappingURL=ng-fab-form.min.js.map

I'm sure it's a quick tweak in the gulpfile that I can look at when I get a chance.  Although it might honestly be better to just not output the sourcemappingurl in the distributed files.

**Comment by johannesjo** [comment]
That would be great!

**Comment by barefootdeveloper** [comment]
Which one just not outputting it for the distributed files?

**Comment by johannesjo** [comment]
I deactivated them altogether. At a later point of time, I might switch to gulp for this project or at least refactor the whole Gruntfile and folder-structure. 

Thank you for the hint!

**Comment by barefootdeveloper** [comment]
Excellent thanks!
