### ISSUE TITLE
Implement handling for groups of inputs (radios)

### ISSUE THREAD

**Issue by xing-zhi** [johannesjo/ng-fab-form#23]
Following image shows the code added in the plunker

![code](https://cloud.githubusercontent.com/assets/6940347/5699486/39bf1526-9a64-11e4-9cbf-9bb73582ddf5.png)

And following image shows the outcome
![outcome](https://cloud.githubusercontent.com/assets/6940347/5699492/61ae0d94-9a64-11e4-9627-284ae4f1598c.png)

**Comment by johannesjo** [comment]
Thank you for reporting the issue. 

The styling is far from perfect and intended to be more of a demonstration at this point of time. But when I find the time, I will have a look into it.

**Comment by johannesjo** [comment]
@xing-zhi simple solution for now would be to just use one required attribute and to adjust the insertErrorTpl-function to your needs. I'm also working on a new directive for such cases.

**Comment by johannesjo** [comment]
@xing-zhi After playing around a little with the different options like wrapper directive or a custom directive you can use to place the validations everywhere inside the form, I decided, that using a single required attribute, is the best solution for this use case. But I'm open to suggestions. What would be the behaviour you expect? Do you (or someone else) suggestions how this should be handled?

**Comment by xing-zhi** [comment]
@johannesjo Thank you very much! "Using a single required attribute" is a good solution.  The radios not be selected will be added the error style when the form submited is the behaviour I expect at present. (Sorry about any Chinglish!)

**Comment by johannesjo** [comment]
I'm happy that it works out for you this way. For now I can't think about a elegant solution, as there are too many possible markups for this kind of thing, which might be conflicting with others.
