### ISSUE TITLE
Directive support that adds validation

### ISSUE THREAD

**Issue by jvelezc** [johannesjo/ng-fab-form#24]
A way to add "a loading bar"   for the state $pending 
and also include the validation for SSN in the ng-fab-form that is returned by deferred.Resolve()
(i dont seem to be able to figure out how to input in the description!
'<input unique-social name="ssn" ng-model="ssn"
                       ng-model-options="{ updateOn: 'default blur', debounce: { 'default': 300, 'blur': 0 } }"
                       ng-required="true"
                       ng-minlength="9"
                       ng-maxlength="9"
                       placeholder="Social Security Number"
                       class="form-control" />
</code>'
    <span ng-show="addEmployee.ssn.$pending">Checking Availability . . .</span>
                <div ng-messages="addEmployee.ssn.$error ">
                    <div ng-message="unique">This SSN already exist in the database</div>
                </div>
            </div>

 <script type="text/javascript">

        (function () {
            var addEmployeeModule = angular.module("addEmployeeModule", ["kendo.directives", 'ngMessages', 'ngAnimate', 'ngFabForm']);

            addEmployeeModule.config(function (ngFabFormProvider) {
                ngFabFormProvider.extendConfig({
                    setAsteriskForRequiredLabel: true
                });
            });

            addEmployeeModule.controller("AddEmployee", function ($scope, ngFabForm) {
                $scope.formOpt = ngFabForm.config;
                $scope.validationMessages = ngFabForm.validationMessages;
                $scope.advancedValidations = ngFabForm.advancedValidations;
    
            });

          
            addEmployeeModule.directive('uniqueSocial', function (isUsernameAvailable) {
                return {
                    restrict: 'A',
                    require: 'ngModel',

                    link: function ($scope, element, attrs, ngModel) {
                        //The reason we use unique on  <div ng-message when="unique" class="error">This is taken</div>
                        //is because we set a ngModel async validator called unique
                        ngModel.$asyncValidators.unique = isUsernameAvailable;

                    }
                }
            });
            addEmployeeModule.factory('isUsernameAvailable', function ($q, $http) {
                return function (ssn) {

                    console.log(ssn);
                    // You may be wondering where ssn this comes from. That is:
                    //<input type name ="ssn"/>
                    var deferred = $q.defer();
                    //Check is the ssn has not been entered at all before beggining to validate
                    if (angular.isUndefined(ssn) || ssn === '') {
                        deferred.resolve();
                    }
                    else {
                        $q.all([$http.post('/api/IsSocialSecurityAvailable/' + ssn)]).then(function (data) {
                            console.log(data);
                            deferred.reject(data);

                        }, function (error) {
                            console.log(error);
                            deferred.resolve(error);
                        });
                    }
                    return deferred.promise;
                }
            });
        }());

       
</script>

**Comment by johannesjo** [comment]
I'm not familiar how this stuff should work normally. Could you provide a full example how you would implement this with vanilla angular?

I'm pretty sure something like this should work either inside of your custom validation template or just in your usual form markup:
```html
<your-loading-bar  ng-show="field.$pending"></your-loading-bar>
<!-- or -->
<your-loading-bar  ng-show="form.$pending"></your-loading-bar>
```

**Comment by jvelezc** [comment]
yes it did work
 but loading bar would be nice when is searching the database 


Sent with the Samsung Galaxy Exhilarate™, an AT&T 4G LTE smartphone.

-------- Original message --------
Subject: Re: [ng-fab-form] Directive support that adds validation (#24)

**Comment by jvelezc** [comment]
i will write up a full example in code pen and get back to you


Sent with the Samsung Galaxy Exhilarate™, an AT&T 4G LTE smartphone.

-------- Original message --------
Subject: Re: [ng-fab-form] Directive support that adds validation (#24)

**Comment by johannesjo** [comment]
@jvelezc thank you!

**Comment by johannesjo** [comment]
@jvelezc ping

**Comment by johannesjo** [comment]
I'll close this due to inactivity. Feel free to reopen.

**Comment by jvelezc** [comment]
k I am so busy once I have the example I will post it.
