### ISSUE TITLE
Support for async validators

### ISSUE THREAD

**Issue by Karabur** [johannesjo/ng-fab-form#25]
Looks like ng-fab-form completely ignores existence of async validators.

**Comment by johannesjo** [comment]
How should that support look like? Habe you tried adjusting the Template file to your needs. Most asynch validators are non generic, so it makes sense to me, to configure their messages and conditions manually. I'm open to suggestions though.

**Comment by johannesjo** [comment]
```
<your-loading-bar  ng-show="field.$pending"></your-loading-bar>
<!-- or -->
<your-loading-bar  ng-show="form.$pending"></your-loading-bar>
```

**Comment by Karabur** [comment]
I was referring to problem if there is $asyncValidators are not empty, but $validators are, validation messages template are not added to input, and field are treated as without validators. 
I've worked around that by adding in validation directive dummy function to $validators array which always return true, but it does not looks like good way. Once I did that, all other things are working fine. 

Library should take into account $asyncValidators array also then it detects existence of validators. 

Messages itself could be configured in Template, indeed, it works well.

**Comment by johannesjo** [comment]
I get your point now. Could you please test it with the latest version from github (not from bower)?

**Comment by Karabur** [comment]
Still the same

**Comment by johannesjo** [comment]
Could you provide a test case (maybe a plunkr based on the one provided)? That would be really nice!

**Comment by johannesjo** [comment]
Sorry for coming back on this one so lately. Actually I don't have any issues with async-valiators. I also provided a test case. If the issue still persists for you, feel free to reopen.
