### ISSUE TITLE
Getting Injector Error

### ISSUE THREAD

**Issue by vishsid73** [johannesjo/ng-fab-form#27]
Hi,

I am getting this error after adding 'ngFabForm' to my module dependency

![fabform](https://cloud.githubusercontent.com/assets/3729892/5974570/c89d5664-a89b-11e4-8e6a-27ef05286420.png)
Error: [$injector:unpr] Unknown provider: $templateRequestProvider <- $templateRequest <- ngFabFormDirective <- inputDirective

why is this so.

Please guide

**Comment by johannesjo** [comment]
Which version of angular are you using? ng-fab-form at least requires v1.3. Can you inject $templateRequest without using ng-fab-form?

**Comment by vishsid73** [comment]
i am using angular 1.2.23.
I haven't added ng-Fab-Form anywhere. just added as the dependency and the error came up. No idea how it is interfering with $templateRequest.

**Comment by johannesjo** [comment]
Did you try using angular 1.3?

**Comment by vishsid73** [comment]
Updated the bower...Now it's working.
Thanks :-)

**Comment by johannesjo** [comment]
You're welcome :)
