### ISSUE TITLE
Ability to use bootstrap validation classes when displaying errors

### ISSUE THREAD

**Issue by atgillette** [johannesjo/ng-fab-form#28]
Hi,

I've used the customization feature to specify where to add error messaging:

.config(function (ngFabFormProvider) {
		var customInsertFn = function (compiledAlert, el, attrs) {
				el.parent().after(compiledAlert);
		};

		ngFabFormProvider.setInsertErrorTplFn(customInsertFn);
	})

But now I'm looking for a way to add and remove bootstrap validation classes to the parent element.

**Comment by johannesjo** [comment]
With v.1.1.9 there is no longer an class-less wrapper element. You should be able to modify the class-name by changing the template itself.

**Comment by atgillette** [comment]
Thanks for the suggestion.  I'm using angular-bootstrap-show-errors module with yours.
