### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by atgillette** [johannesjo/ng-fab-form#30]
Hi,

Does your module support or plan to support i18n?

**Comment by johannesjo** [comment]
Have you tried using [angular-translate](https://github.com/angular-translate/angular-translate)? It should work nicely together with ng-fab-form. To do so, you can edit the template.

While it should be quite easy to implement such functionality within ng-fab-form, I'm not sure if the module should be really responsible for translations as their probably is not only relevant for validations.

**Comment by atgillette** [comment]
Thanks for the suggestion @johannesjo.  I was able to use angular-translate with your module.  I even got it to work with their partial loader.  Nice indeed.
