### ISSUE TITLE
Passwords

### ISSUE THREAD

**Issue by wgorder** [johannesjo/ng-fab-form#32]
Looks nice I am about to try it out. Looking at it would be neat if could support matching password validation (common scenario on registration forms)..

Also some of the English needs to be touched up in the default messages.  Looks very nice though, thank you.

**Comment by johannesjo** [comment]
Interesting suggestion. Should be easy to implement. For now you can use:
https://github.com/TheSharpieOne/angular-input-match (untested by me)

**Comment by johannesjo** [comment]
I'll added a match directive. Have a look at the readme to find out if it works for you.

**Comment by wgorder** [comment]
Perfect looks good.  I'll open a pull request with some suggestions for the English stuff.  Thanks again and nice work!
