### ISSUE TITLE
Async Validation

### ISSUE THREAD

**Issue by Oldwo1f** [johannesjo/ng-fab-form#34]
Hello
I am currently trying ng-fab-form. And i have troubles with "unique validation".
For exemple, if an user try to register with an already used email adress. He ll cross the frontend validation but not the backend.

It is this backend error that i want to report on the email field's  error message.

Can you explain me a way to achieve that.

Thanks.

Btw : Great job for this module

**Comment by johannesjo** [comment]
Hello. There are lots of tutorials [out there](https://www.google.de/search?q=anugalr+async+tutorial&oq=anugalr+async+tutorial&aqs=chrome..69i57.4519j0j7&sourceid=chrome&es_sm=93&ie=UTF-8#q=angular+async+validation+tutorial&spell=1). To implement it with ng-fab-form you just have to add a line to the validation template like you would with using ng-message:
```
<li ng-message="unique">Your message</li>
```
