### ISSUE TITLE
Question - Validation success class

### ISSUE THREAD

**Issue by wgorder** [johannesjo/ng-fab-form#35]
Hi. I like the effect you have on your demo, with the green checkmark.  However I noticed that if you hide and show the form using ng-if or show/hide etc.  That the validation-success effect is shown briefly.  Do you know of a way to prevent that?

**Comment by johannesjo** [comment]
Thank you for pointing that out! It should be fixed with the new release 1.1.14

Just for the record: It actually was related to an issue with the compilation of the validation message template. I had to wrap the insert function into a timeout to wait for the form variables to be evaluated.
