### ISSUE TITLE
Add option to make using custom validation expressions easier (e.g. input:type=email)

### ISSUE THREAD

**Issue by wgorder** [johannesjo/ng-fab-form#38]
Could be better:

www.google.com is not valid
and 
http://g is 

Things I would expect to be valid:
http://google.com
https://google.com 
~~www.google.com~~  [Edit - the spec says there needs to be a scheme to be valid]
http://www.google.com
https://www.google.com

**Comment by johannesjo** [comment]
Thanks for reporting. ng-fab-form is using angulars default validators (with the exception of the email validator) and angulars validators are using the browsers default. While I feel comfortable to assume that the default email-validation is not what most people would want, I do less so about urls.

**Comment by wgorder** [comment]
Yeah it looks like angular just did a poor job.  I don't think anyone would want http://g to validate to valid.  However that is fair I can use a pattern instead.

**Comment by wgorder** [comment]
Ok so after some reading this (and e-mail) are hot topics with a lot of debate.  Angular validates only what the spec technically requires. Unfortunately that falls far short of the 99% use case.  There recommendation appears to be to use a pattern or to decorate their directives to provide the more standard validation rules.

For the next guy coming along here is a useful thread about the URL:
https://github.com/angular/angular.js/issues/6634

**Comment by johannesjo** [comment]
For the record: This is how ng-fab-form overwrites the email-validation:
```
// overwrite email-validation
                            if (cfg.emailRegex && attrs.type === 'email') {
                                ngModelCtrl.$validators.email = function (value)
                                {
                                    return ngModelCtrl.$isEmpty(value) || cfg.emailRegex.test(value);
                                };
                            }
```

I'll think about providing an option to overwrite the standard validators more easily.

**Comment by johannesjo** [comment]
I added a new api for this feature. Its available in the latest build.

**Comment by wgorder** [comment]
Thanks!
