### ISSUE TITLE
Success Validation shows before field has had focus

### ISSUE THREAD

**Issue by wgorder** [johannesjo/ng-fab-form#39]
The green checkmark shows right away on a field that does not have validation constraints e.g. is not required.  I would say that it should follow the same rules as error messages and not show until the form is submitted, or has received focus

**Comment by johannesjo** [comment]
Thank you for reporting! I'm not able to reproduce this behavior however. Fields without any validation rules don't show any success-mark for me (check out the plunkr). Would be really nice if you could provide a plunkr.

You should also be able to adjust the default behavior by editing the validation template, if the default config doesn't fit your taste.

**Comment by wgorder** [comment]
Interesting.  Its bed time here, but maybe its something with my setup.  I'll try to reproduce this and post back here.

**Comment by wgorder** [comment]
It appears to apply to input[type="url"].  Edit your demo site plunkr as follows and you will see it.

```
<div class="form-group">
                <label>non required</label>
                <input type="url"
                       class="form-control"
                       placeholder="TestText"
                       ng-model="formData.nonRequired">
            </div>

```
