### ISSUE TITLE
Consider using the non-minified version in bower-main

### ISSUE THREAD

**Issue by wgorder** [johannesjo/ng-fab-form#41]
The reason being many front end developers use gulp, grunt or a similar build tool which does this for you.  If you are not using these build  tools you are probably not using bower either, or you can include the minified version if you want.  Having it already minified messes up these tools.

Also if your like me I like to serve the non-minified version during development.  I only minify on production build. What gets served is what is defined in the main of the bower file.

Also that is the official recommendation, see here:

See https://github.com/bower/bower/issues/393

`Current spec description:`

The primary acting files necessary to use your package. While Bower does not directly use these files, they are listed with the commands bower list map and bower list --sources, so they can be used by build tools. **Do not include minified files.** Files should not be versioned (Bad: package.1.1.0.js; Good: package.js).

**Comment by johannesjo** [comment]
Thanks for the suggestion. I wasn't aware that this is a bad practice to do so. I'll change that.
