### ISSUE TITLE
ngAnnotate() with ng-strict-di

### ISSUE THREAD

**Issue by wgorder** [johannesjo/ng-fab-form#44]
Thanks for providing the uniminified version in bower main!  I have one more request.  I use ng-strict-di="true" on my application, and when I pull in the unminified version it is throwing errors.  Do you suppose you could add the ngAnnotate() build step before producing the unminified js file as well and not just as a part of the uglify step?

That way both the uniminified and minified versions would pass the ng-strict checks.

**Comment by johannesjo** [comment]
I'll try to have a look into it on the weekend. Feel free to provide a PR until then :) Just wondering: Why would you use ngStrictDi?

**Comment by wgorder** [comment]
I have found that in some cases ng-annotate drops the ball.  This annotation give you immediate feedback by throwing an error if something is not minification safe.  That way you don't have nasty surprises when you deploy minified code but develop with unminified code.  Also the errors are then meaningful and its easy to track down versus the ones you get on the unminified version.  It is also the recommendation to use it, as stated in ng-annotate docs.

**Comment by wgorder** [comment]
FYI here is an topic on it.
https://github.com/olov/ng-annotate/issues/142

**Comment by johannesjo** [comment]
I added the annotation task a little earlier. ngStrictDi should now work.
