### ISSUE TITLE
Add a way to wait for form controller to initialize

### ISSUE THREAD

**Issue by wgorder** [johannesjo/ng-fab-form#45]
I must be doing something wrong.  I have a component that looks like this:

```
      <div class="form-group">
          <label for="{{formName+index}}" class="col-md-4 control-label">{{label}}</label>
          <div class="col-md-8">
              <textarea ng-minlength="minLength" ng-readonly="readOnly" ng-maxlength="maxLength" ng-model="inputText" ng-required="required" id="{{formName+index}}" rows="{{rows}}" class="form-control" placeholder="{{placeholder}}"/>
              <p class='help-block'>{{description}}</p>
          </div>
      </div>
```
For whatever reason for textAreas the validation template for ng-fab-form is not being appended to text area elements.  Do you see something wrong with the above?  Any idea where I should look.  It is appended properly to inputs.

**Comment by johannesjo** [comment]
Just a guess: Could be that the id-attribute. Otherwise: Weird, the directive code for inputs and textareas is exactly the same...

**Comment by johannesjo** [comment]
Ok reason seems to be ```ng-required="required"```. Required is a scope-variable ($scope.required) in this context, which - I suppose - resolves to undefined. 

So why all of these work:
```
ng-required="true"
required="required"
required
```
```ng-required="required"``` does not.

**Comment by wgorder** [comment]
I am using the same ng-required on the inputs and that seems fine.  The invalid classes are all on the text area but for whatever reason the entire validation template has not been appended to the text area so the validation message does not show up.  I cant figure out what is different.  Do they have to have names or unique names etc?

**Comment by wgorder** [comment]
I am using it with a heavily modified version of this library (I am not using his validation stuff). 

https://github.com/kelp404/angular-form-builder/blob/master/components/default-components.coffee

But the way it works is all the components on the page have the same ng-model attribute backing it, so if a name is derived somehow from the model it is probably that the components are having the same name...

**Comment by johannesjo** [comment]
They have the same ng-model attribute? What do you mean by that?

**Comment by wgorder** [comment]
If you look at the link in his template all the form elements on the page regardless of what they are have 
`ng-model="inputText"`

**Comment by johannesjo** [comment]
Are the validation-messages (their container) completely missing from the compiled html or are they just not displayed?

**Comment by wgorder** [comment]
completely missing

**Comment by johannesjo** [comment]
This could mean that the insertValidationMsgs-function inside of the [inputs-directive](https://github.com/johannesjo/ng-fab-form/blob/master/src/ng-fab-form-validations-directive-f.js) is never called. Could you debug around this and report back to me? That would be nice!

**Comment by wgorder** [comment]
Its definitely called for inputs.  I think maybe its just not called for textareas (and text areas work fine in another application I am using your library)

It looks like you simply target elements of type textarea and append the validation container template to it.  I was wondering if there was anything you knew of that would prevent that event from happening, as it seems to be what is happening.  I will keep digging.

**Comment by johannesjo** [comment]
This is the condition (same file, line 111):
```
if (ngModelCtrl && cfg.validationsTemplate && ((Object.keys(ngModelCtrl.$validators).length !== 0) || (Object.keys(ngModelCtrl.$asyncValidators).length !== 0)) && (!oldCfg || cfg.validationsTemplate !== oldCfg.validationsTemplate)) {
```
I hope this helps.

**Comment by sajidali** [comment]
> If theIf you look at the link in his template all the form elements on the page regardless of what they are have ng-model="inputText"

@wgorder  you can manually write name attribute in <textarea name="{{inputText}}{{$index}}]" .... >
If textarea/fields are rendered in ng-repeat, $index will always be unique otherwise, use any unique identifere in the name, and you should be good to go.

**Comment by wgorder** [comment]
OK. So that if check is not even happening for textareas.  It looks like the problem is sooner.  Here is the form that is rendered in the browser.  You will see the text area is missing the validation template.

```
<form class="form-horizontal ng-pristine ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-valid ng-valid-required" name="ngFabForm_7170c462_626d_4ee9_ab26_033e36e18e5a" novalidate="true">
    <div ng-model="input" fb-form="default" fb-default="defaultValue" class="ng-pristine ng-untouched ng-valid ng-isolate-scope"><!-- ngRepeat: object in form --><div class="fb-form-object ng-scope" ng-repeat="object in form" fb-form-object="object"><div class="form-group ng-scope ng-hide" ng-hide="$root.hideFormAttribute(label)">
    <label for="default0" class="col-md-4 control-label ng-binding">Schema Prefix</label>
    <div class="col-md-8" ng-switch="inputType">
        <!-- ngSwitchWhen: text --><input type="text" ng-switch-when="text" ng-minlength="" ng-readonly="readOnly" ng-maxlength="" ng-pattern="" ng-model="inputText" ng-required="required" id="default0" class="form-control ng-pristine ng-untouched ng-valid ng-scope ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-valid-required" placeholder="The column header prefix" name="inputText"><div ng-messages="field.$error" ng-show="attrs.required==''|| attrs.required" class="validation ng-scope ng-inactive">
  <ul ng-show="field.$invalid &amp;&amp; (field.$touched || field.$dirty || form.$triedSubmit)" class="list-unstyled validation-errors ng-hide">
    <!-- ngMessage: required -->
    <!-- ngMessage: password -->
    <!-- ngMessage: email -->
    <!-- ngMessage: pattern -->
    <!-- ngMessage: date -->
    <!-- ngMessage: time -->
    <!-- ngMessage: datetime -->
    <!-- ngMessage: datetime-local -->
    <!-- ngMessage: number -->
    <!-- ngMessage: color -->
    <!-- ngMessage: range -->
    <!-- ngMessage: month -->
    <!-- ngMessage: url -->
    <!-- ngMessage: file -->
    <!-- ngMessage: minlength -->
    <!-- ngMessage: maxlength -->
    <!-- ngMessage: match -->
    <!-- ngIf: attrs.type == 'time' -->
    <!-- ngIf: attrs.type == 'time' -->
    <!-- ngIf: attrs.type == 'number' -->
    <!-- ngIf: attrs.type == 'number' -->
    <!-- ngIf: attrs.type == 'date' -->
    <!-- ngIf: attrs.type == 'date' -->
  </ul>
  <div ng-show="field.$valid &amp;&amp; !field.$invalid" class="validation-success"></div>
</div><!-- end ngSwitchWhen: -->
        <!-- ngSwitchWhen: number -->
        <!-- ngSwitchWhen: email -->
        <!-- ngSwitchWhen: url -->
        <p class="help-block ng-binding"></p>
    </div>
</div></div><!-- end ngRepeat: object in form --><div class="fb-form-object ng-scope" ng-repeat="object in form" fb-form-object="object"><div class="form-group ng-scope" ng-hide="$root.hideFormAttribute(label)">
    <label for="default1" class="col-md-4 control-label ng-binding">Name</label>
    <div class="col-md-8" ng-switch="inputType">
        <!-- ngSwitchWhen: text --><input type="text" ng-switch-when="text" ng-minlength="" ng-readonly="readOnly" ng-maxlength="" ng-pattern="" ng-model="inputText" ng-required="required" id="default1" class="form-control ng-pristine ng-untouched ng-scope ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-valid ng-valid-required" placeholder="Enter a name" name="inputText" required="required"><div ng-messages="field.$error" ng-show="attrs.required==''|| attrs.required" class="validation ng-scope ng-inactive">
  <ul ng-show="field.$invalid &amp;&amp; (field.$touched || field.$dirty || form.$triedSubmit)" class="list-unstyled validation-errors ng-hide">
    <!-- ngMessage: required -->
    <!-- ngMessage: password -->
    <!-- ngMessage: email -->
    <!-- ngMessage: pattern -->
    <!-- ngMessage: date -->
    <!-- ngMessage: time -->
    <!-- ngMessage: datetime -->
    <!-- ngMessage: datetime-local -->
    <!-- ngMessage: number -->
    <!-- ngMessage: color -->
    <!-- ngMessage: range -->
    <!-- ngMessage: month -->
    <!-- ngMessage: url -->
    <!-- ngMessage: file -->
    <!-- ngMessage: minlength -->
    <!-- ngMessage: maxlength -->
    <!-- ngMessage: match -->
    <!-- ngIf: attrs.type == 'time' -->
    <!-- ngIf: attrs.type == 'time' -->
    <!-- ngIf: attrs.type == 'number' -->
    <!-- ngIf: attrs.type == 'number' -->
    <!-- ngIf: attrs.type == 'date' -->
    <!-- ngIf: attrs.type == 'date' -->
  </ul>
  <div ng-show="field.$valid &amp;&amp; !field.$invalid" class="validation-success"></div>
</div><!-- end ngSwitchWhen: -->
        <!-- ngSwitchWhen: number -->
        <!-- ngSwitchWhen: email -->
        <!-- ngSwitchWhen: url -->
        <p class="help-block ng-binding"></p>
    </div>
</div></div><!-- end ngRepeat: object in form --><div class="fb-form-object ng-scope" ng-repeat="object in form" fb-form-object="object"><div class="form-group ng-scope">
    <label for="default2" class="col-md-4 control-label ng-binding">Description</label>
    <div class="col-md-8">
        <textarea ng-minlength="" ng-readonly="readOnly" ng-maxlength="" ng-model="inputText" ng-required="required" id="default2" rows="6" class="form-control ng-pristine ng-untouched ng-valid-minlength ng-valid-maxlength ng-valid ng-valid-required" placeholder="Enter a description" name="inputText" required="required"></textarea>
        <p class="help-block ng-binding"></p>
    </div>
</div></div><!-- end ngRepeat: object in form --></div>
  </form>
```

**Comment by johannesjo** [comment]
Only three possible reasons for that:
1. There is no form-controller.
2. There is no ngModel-controller.
3. The directive is never compiled for textareas.

**Comment by wgorder** [comment]
Ok here is the culprit

```
                    $timeout(function ()
                    {
                        // only execute if formCtrl is set
                        if (formCtrl && ngModelCtrl) {
```

formCtrl is null on the textArea.. I have no idea why

**Comment by johannesjo** [comment]
This could be related to no names being assigned (here)[https://github.com/kelp404/angular-form-builder/blob/master/components/default-components.coffee]. Maybe you can overwrite the templates?

**Comment by wgorder** [comment]
I tried playing with that but it did not help.  Plus it does not explain why it works as is for inputs.  If you look at the rendered HTML above you will see there is a name attribute on everything.

**Comment by johannesjo** [comment]
Well actually I would write a ticket for angular-form-builder. The form controller not being present at this point could lead to other incompatibilities too.

**Comment by wgorder** [comment]
Yeah, I don't think its really maintained.  I have made modifications myself at this point.  I  could easily make the change but I am not sure where to do it.  I don't see any special handling for text areas and the form controller is available for inputs.  I am still stuck here.

**Comment by johannesjo** [comment]
Might be that the form-controller is lost due to some isolate scope being established. I always thought that this does not matter for require though.

**Comment by wgorder** [comment]
Yeah.  The more I look the more I am confused.  This is actually how the form is defined (see the below jade markup)
```
  form.form-horizontal(name="templateForm" ng-submit="modalSave(input)")
    div(ng-model='input', fb-form='default', fb-default='defaultValue')
```
As you can see the form is actually defined by me outside of his directive.  His directive is queued by the fb-form attribute on the div inside the form.  It then injects the components of the form.  There is no special treatment from one type of component to the next.  It simply puts them in there they way they are defined in the template, and yet input works and text are does not.  This would be more straightforward if nothing worked.

**Comment by wgorder** [comment]
I am starting to wonder if this is a timing issue.  The inputs are loaded after selects, text areas etc.  I wonder if it just has not initialized yet.

**Comment by johannesjo** [comment]
Not without altering the child-directive to my knowledge. You can use $inject to see if it exists though.

**Comment by wgorder** [comment]
Man.  Yeah that was it.  I changed the template to this

```
      <div class="form-group">
          <label for="{{formName+index}}" class="col-md-4 control-label">{{label}}</label>
          <div class="col-md-8" ng-switch="foo">
              <input type="text" ng-switch-when="text" ng-minlength="minLength" ng-readonly="readOnly" ng-maxlength="maxLength" ng-pattern="pattern" ng-model="inputText" ng-required="required" id="{{formName+index}}" class="form-control" placeholder="{{placeholder}}"/>
              <input type="number" ng-switch-when="number" ng-min="min" ng-max="max" ng-readonly="readOnly" ng-model="inputText" ng-required="required" id="{{formName+index}}" class="form-control" placeholder="{{placeholder}}"/>
              <input type="email" ng-switch-when="email" ng-readonly="readOnly" ng-maxlength="maxLength" ng-pattern="pattern" ng-model="inputText" ng-required="required" placeholder="{{placeholder}}" id="{{formName+index}}" class="form-control"/>
              <input type="url" ng-switch-when="url" ng-minlength="minLength" ng-readonly="readOnly" ng-maxlength="maxLength" ng-pattern="pattern" ng-model="inputText" ng-required="required" id="{{formName+index}}" class="form-control" placeholder="{{placeholder}}"/>
              <textarea ng-switch-default ng-minlength="minLength" ng-readonly="readOnly" ng-maxlength="maxLength" ng-model="inputText" ng-required="required" id="{{formName+index}}" rows="{{rows}}" class="form-control" placeholder="{{placeholder}}"/>
              <p class='help-block'>{{description}}</p>
          </div>
      </div>
```

now this switches on the value of 'foo' which does not even exist.  However it takes just long enough to execute those additional checks that by the time it makes it to the switch default (the text area) the form controller has initiallized.

So the problem appears to be that your directive activates on the enclosing form tag.  The inner div has a directive that adds additional form elements to the DOM.  However your link function gets called before the form controller for that new element has initialized.  Creating some extra logic in the rendering decision give the time needed to finish creating that controller.  Ideally what I need is a way for in the fab form directive to say 'wait for the formController to initialize'

**Comment by johannesjo** [comment]
I'll try to think about a way. There are quite some possible performance issues related to this one. Imho the issue is still with the form builder. A possible alternative would be an option to provide an optional bootstrap mechanism like angular does. Another one to provide an configurable initial delay. I'm not sure...

**Comment by wgorder** [comment]
If you have a  suggestion on how to fix it in the form builder I am happy to make the change.  He does not maintain his stuff or seemingly merge any pull requests so I have basically used his stuff as a starting point and made many modifications at this point anyway.  There is not much interesting to see in his directive though.  

The directive that triggers everything is below in its entirety
```
.directive 'fbForm', ['$injector', ($injector) ->
  restrict: 'A'
  require: 'ngModel'  # form data (end-user input value)
  scope:
    # input model for scops in ng-repeat
    formName: '@fbForm'
    input: '=ngModel'
    default: '=fbDefault'
  template:
    """
    <div class='fb-form-object' ng-repeat="object in form" fb-form-object="object"></div>
    """
  controller: 'fbFormController'
  link: (scope, element, attrs) ->
    # providers
    $builder = $injector.get '$builder'

    # get the form for controller
    $builder.forms[scope.formName] ?= []
    scope.form = $builder.forms[scope.formName]
]
```

Once the new tag is added it triggers another directive that inserts each compoent.  That directive is declared as follows:

```
.directive 'fbFormObject', ['$injector', ($injector) ->
  # providers
  $builder = $injector.get '$builder'
  $compile = $injector.get '$compile'
  $parse = $injector.get '$parse'

  restrict: 'A'
  controller: 'fbFormObjectController'
  link: (scope, element, attrs) ->

```

I think any directive that changes the underlying DOM(inside the form tag) is going to suffer from this.  I am not sure how to fix it inside the form builder (if you know please tell :) ), but as you say a delay at the higher level e.g. inside fab-form would have to be a deliberate choice,  to cover use cases where people want to dynamically change the form.

I guess one option that might possible work would be to have the form builder template insert the form tag  rather than just the components.  If it did this your directive would not trigger until the form builder was finished... I think.

so rather than

```
 <div class='fb-form-object' ng-repeat="object in form" fb-form-object="object"></div>

```
it would be 

```
<form>
<div class='fb-form-object' ng-repeat="object in form" fb-form-object="object"></div>
</form>
```

Not sure if that would work or not.

**Comment by wgorder** [comment]
Ill answer my own question.  That didn't work :(

**Comment by wgorder** [comment]
Ahh yes, your right.  I see one of your directives activates on the form but the ones we are talking about are on the element tag, select, input, textarea etc.

**Comment by johannesjo** [comment]
Just a quick headsup: I found a solution. 
```
formCtrl = el.controller('form');
```
instead of requiring the form-controller, which gets lost, when the ng-model element is created later or is in a different non-child scope. This changes a lot, and I'm not sure about all the implications, though all tests pass.

**Comment by wgorder** [comment]
Nice find!  I didn't even know you could do that.

**Comment by wgorder** [comment]
Hmm that is not working for me.  It actually always seems to return undefined.  I tried put it in the initial assignment also I tried it in the $timeout function with an if check.

```
 if(!formCtrl) {
    formCtrl =  el.controller('form');
 }
```
In both cases it was always undefined.  I actually expected it to be defined at least in the case of the inputs as they took long enough to process that the form controller has always been present for them.

**Comment by johannesjo** [comment]
It needs to be put in the input-elements-directive.

**Comment by wgorder** [comment]
Ok when I put it there its not null there,  but I am still having issues because there are dependencies on it in the linking function of the form directive

```
 return {
            restrict: 'E',
            require: ['?^form', '?ngModel'],
            compile: function (el, attrs)
``` 

```
function ngFabFormCycle(oldCfg)
                    {
                        // apply validation messages
                        // only if required controllers and validators are set
                        if (ngModelCtrl && cfg.validationsTemplate && ((Object.keys(ngModelCtrl.$validators).length !== 0) || (Object.keys(ngModelCtrl.$asyncValidators).length !== 0)) && (!oldCfg || cfg.validationsTemplate !== oldCfg.validationsTemplate)) {
                            insertValidationMsgs({
                                scope: scope,
                                el: el,
                                cfg: cfg,
                                formCtrl: formCtrl,
                                ngModelCtrl: ngModelCtrl,
                                attrs: attrs,
                                currentValidationVars: currentValidationVars
                            });
                        }
```

I guess once you have your proposed solution out Ill just test again. I am moving on with my hack fix for now, as I have a deadline and then I can loop back around and play some more.

**Comment by johannesjo** [comment]
The new release should fix the issue.

**Comment by wgorder** [comment]
Nice work!  That fixed it,  and its a worthy improvement as well I think.  I can see this issue having come up in other scenarios as well.

Feel free to close this issue.
