### ISSUE TITLE
Duplicate Form warning

### ISSUE THREAD

**Issue by wgorder** [johannesjo/ng-fab-form#50]
Can we have a way to disable this via config?

Currently it triggers when I have a form that is conditionally shown. Even though it is not a duplicate form it is still printing the message.  Note it does not show the message initially but if the form is removed and then re-added to the dom it triggers the warning.

**Comment by johannesjo** [comment]
Good idea! Thank you. I'll get on to that on the weekend.

**Comment by johannesjo** [comment]
Would be nice if you could also provide a test-case for that scenario. I'm also working on a version without the form-name requirement, but I'm not yet sure if that will work out for everything.

**Comment by johannesjo** [comment]
I removed the name requirement entirely with v1.2.4 so the issue should not occur again.

**Comment by wgorder** [comment]
Thanks!  Sorry I had not gotten to a test case yet, I guess it would be unnecessary now.
