### ISSUE TITLE
Does not work with dynamic data

### ISSUE THREAD

**Issue by tushariscoolster** [johannesjo/ng-fab-form#51]
Suppose i dynamically add element by javascript;

i cant see validation error
here is code snipped

/*@description:to upload video to aws and execute the function*/
app.directive('select, function ($parse,$compile) {
    return {
        link: function (scope, elm, attr, ngModelCtrl) {

            var html = "<input type='text' class='uiselectclass' ng-model=" + attr.ngModel + " required/>"
            var angualarHtml = $compile(html)(scope);
            elm.after(angualarHtml)
        }
    };
});

**Comment by johannesjo** [comment]
Thanks for reporting! Can you actually see the standard classes like ng-invalid and the like on the element?

Also it needs to be wrapped in a form to work.

**Comment by tushariscoolster** [comment]
Yes i can see, but i am not able to see the error template appending to dom

**Comment by johannesjo** [comment]
Thank you. I'll dig into that. Could you by any chance provide a plunkr? That would be most helpful! :)

**Comment by johannesjo** [comment]
Works for me. You probably shouldn't use select as an directive name. Might also be you're not using the latest version of ng-fab-form.

**Comment by tushariscoolster** [comment]
Yeh may be version problem
http://plnkr.co/edit/WPwKs70UXwARg6SctDQU?p=preview
Thanks

**Comment by johannesjo** [comment]
If you have a problem like this, you might also wanna try the waitForFormCtrl option.

**Comment by tushariscoolster** [comment]
Thanx a lot man;

**Comment by johannesjo** [comment]
You're welcome!
