### ISSUE TITLE
ng-maxlength without required

### ISSUE THREAD

**Issue by devphil0** [johannesjo/ng-fab-form#52]
Is there a way I can check the maxlength of a string without attaching the required tag?

**Comment by johannesjo** [comment]
You can edit the validations template to do so:
```
<div ng-messages="field.$error"
     class="validation"
     ng-show="attrs.required==''|| attrs.required">
```
Just remove the ng-show condition here.

**Comment by devphil0** [comment]
Thanks alot!

**Comment by johannesjo** [comment]
Hm weird. That should work. I assume your input is wrapped into a form?

**Comment by johannesjo** [comment]
ping @devphil0 .

**Comment by devphil0** [comment]
As you're assuming, I wrapped the input into a form. The directive input-decimal allows decimal numbers only. 

I'm using the html-attribute maxlength as solution - you can close this issue.
Thanks for your deployment.
