### ISSUE TITLE
add class to form, when submit was attempted

### ISSUE THREAD

**Issue by devphil0** [johannesjo/ng-fab-form#53]
Is there a way to set the border of a inputbox after I hit the submit button?
Your example just handles the leave- and enter events

**Comment by johannesjo** [comment]
What do you want to achieve with that?

**Comment by devphil0** [comment]
Exactly. In your example you only show the red border when when you leave the inputbox. I want to show the red border when the input is invalid

**Comment by johannesjo** [comment]
Well, there is unfortunately no class added for that yet. But you could do it like this:
```
<form name="blaForm"
          ng-class="{'your-parent-form-tried-submit-class': blaForm.$triedSubmit}>
</form>
```

**Comment by johannesjo** [comment]
I think this feature is not too imortant. If someone really needs it, feel free to reopen.
