### ISSUE TITLE
Add validation to ensure expression

### ISSUE THREAD

**Issue by tushariscoolster** [johannesjo/ng-fab-form#56]
I have added this directory to ensure condition match,
hoping to integrate in core library
http://plnkr.co/edit/JjMTyh8lEXGIgEUsCpLK?p=preview
Thanks

**Comment by johannesjo** [comment]
Hello @tushariscoolster. Thank you very much for posting this addition! Can you tell me a little bit more about the possible use cases for such a directive?

**Comment by tushariscoolster** [comment]
suppose i want to check that;
targetValue=50;
curretValue=40;
targetValue>curretValue; 
How can you check this with existing directive?

**Comment by johannesjo** [comment]
You can't :) Thinking about it there are definitely use cases for this.

I would gladly accept a pull-request. Would be a good practise to prefix the directive like `ng-fab-match` so `ng-fab-ensure-expression` or something like this.

**Comment by tushariscoolster** [comment]
K making pull request?

**Comment by johannesjo** [comment]
That would be great!

**Comment by johannesjo** [comment]
The only thing missing is the documentation. I'll try to write some during the weekend.

**Comment by tushariscoolster** [comment]
Sure thing, i will get it done in free time
