### ISSUE TITLE
Support for html error messages with validation-msg-*

### ISSUE THREAD

**Issue by tushariscoolster** [johannesjo/ng-fab-form#60]
Should have support to show html as error message
```validation-msg-pattern="<div>Not valid length</div><div>Not valid length</div>"<div>Not valid length</div>```

**Comment by johannesjo** [comment]
You're right, it should! Unfortunately I won't be able to look into this until next week probably the week after that. Pull Requests are always welcome of course :) 

The related function can be found here: https://github.com/johannesjo/ng-fab-form/blob/master/src/ng-fab-form-p.js#L81

**Comment by johannesjo** [comment]
This should work now with the newest release.

**Comment by tushariscoolster** [comment]
Tnx
