### ISSUE TITLE
setAsteriskForRequiredLabel doesn't work in Firefox 37.0.1

### ISSUE THREAD

**Issue by emasch** [johannesjo/ng-fab-form#62]
When I activate setAsteriskForRequiredLabel in Firefox 37.0.1 I got the following Error:

    Error: label.innerText is undefined
    setAsteriskForLabel@http://localhost:8082/portal/static/bower_components/ng-fab-form/dist/ng-fab-form.js:459:1
    ngFabFormCycle@http://localhost:8082/portal/static/bower_components/ng-fab-form/dist/ng-fab-form.js:525:29
    init/<@http://localhost:8082/portal/static/bower_components/ng-fab-form/dist/ng-fab-form.js:556:33
    timeout/timeoutId<@http://localhost:8082/portal/static/bower_components/angular/angular.js:16223:28
    completeOutstandingRequest@http://localhost:8082/portal/static/bower_components/angular/angular.js:4905:7
    Browser/self.defer/timeoutId<@http://localhost:8082/portal/static/bower_components/angular/angular.js:5285:7

    http://localhost:8082/portal/static/bower_components/angular/angular.js
    Line 11607

When I use the IE, it works fine.

**Comment by johannesjo** [comment]
Thank you very much for reporting the issue. Could you by any chance also provide the markup you're using for you form?

**Comment by emasch** [comment]
I use the following markup:

    <form class="form" name="form" ng-submit="register()">
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" id="username" name="username" class="form-control" ng-model="registrationForm.useraccount.username" required autofocus username-validator />
        </div>
    </form>

**Comment by johannesjo** [comment]
I`ll look into it. It's probably related to how document.querrySelector works cross browser.

**Comment by johannesjo** [comment]
This should be fixed, but travis is down for now. I'll merge the fix into master once it is up and running again. Thanks again for reporting the issue!
