### ISSUE TITLE
Watchers are not destroyed

### ISSUE THREAD

**Issue by GoestaBergfeld** [johannesjo/ng-fab-form#63]
I have a directive with a form inside. I have ngFabForms injected. Everything is working fine. But ... after this directive is destroyed (because of a state change via angular-ui-router) I have remaining watchers (identified by ngStats).

**Comment by johannesjo** [comment]
Thanks for reporting! Interesting, I thought they're usually destroyed automatically when the element is removed. I will check this out.

**Comment by johannesjo** [comment]
Would you be so kind to check again?

**Comment by GoestaBergfeld** [comment]
Thanks for your fast reply. I will check it on monday in the office and let you know.

Best regards 
Gösta 

Von meinem iPhone gesendet

**Comment by johannesjo** [comment]
Thank you! Have a nice weekend!

**Comment by GoestaBergfeld** [comment]
Hi, it is working like a charme. All watchers are now removed. Thanks a lot for your quick fix!

**Comment by johannesjo** [comment]
I have to thank you! :) This could have lead too very very hard to debug problems. Now we're covered on this front.
