### ISSUE TITLE
Select with empty value is validated with required attribute but with ng-required attribute, the validation does not work

### ISSUE THREAD

**Issue by sajidali** [johannesjo/ng-fab-form#66]
Select with empty value is validated with required attribute but with ng-required attribute, the validation does not work

check this example, select (required) have ng-required attribute, but even with empty default value, it is shown as valid.
http://plnkr.co/edit/67FVoM?p=preview

When you change ng-required to required, the select box gets validated as expected.

I need ng-required to work, because I want to make the field required based on some condition.
Please help.

**Comment by johannesjo** [comment]
Thanks for reporting. It's not an issue with fab-form though. You need to change your code :)
When using ng-required you need to give it a value: http://plnkr.co/edit/F7gnL02nQiZYoOLfHuxT?p=preview

Using ng-required like in the example basically comes down to 
```
ng-required=""
==> ngRequired = false
==> no required attribute is set
```

**Comment by sajidali** [comment]
Big oops :-1:  on my part. thank you for taking your time to write the response.
