### ISSUE TITLE
Null Reference Error during $destroy

### ISSUE THREAD

**Issue by GoestaBergfeld** [johannesjo/ng-fab-form#67]
Hi, 

just found another bug during $destroy. Please take a look at line 611 I guess and add These if-statements around.

// destroy private scope set for validations
                        if(currentValidationVars){
                            if(currentValidationVars.privateScope){
                                currentValidationVars.privateScope.$destroy();
                            }
                        }

**Comment by johannesjo** [comment]
Thanks for reporting! That should be already fixed with the latest release.
