### ISSUE TITLE
Only use directive on some forms not others.

### ISSUE THREAD

**Issue by jon64digital** [johannesjo/ng-fab-form#71]
Hi,

I've noticed that once you inject ngFabForm into your module every form becomes an ng-fab-form.

Is it possible to make it so that the directive only applies when you explicitly add it. E.g. ......

`<form name="contactForm" ng-fab-form></form>`

..... would be a fab form, but this wouldn't.....

`<form name="contactForm"></form>`

Is this possible?

**Comment by johannesjo** [comment]
Hello Jon,

thank you very much for your suggestion. I'm already working on it. It's a little tricky, but I'm sure there will be a way to enable this feature.

**Comment by johannesjo** [comment]
I'll added the feature to the latest release. Could you check, if it works out for you?
