### ISSUE TITLE
Asterisk for required label and bootstrap 3

### ISSUE THREAD

**Issue by roederb** [johannesjo/ng-fab-form#75]
Hi, according to bootstrap 3 an inputfield with respective label should be written the way i posted a little further down. I noticed that the Asterisk function for required fields does not work for the input field, when i use the method as described in bootstrap 3.
Any help on that issue?            

                <label for="name2" class="control-label col-sm-2">Name 2:</label>

                <div class="col-sm-4">
                    <input class="form-control" type="text" name="name2"
                           ng-model="someModel" required />
                </div>

thanx
Bernd

**Comment by johannesjo** [comment]
This is the query-selector:
```
document.querySelectorAll('label[for="' + attrs.name + '"]');
```
I'm not sure why this shouldn't work with your code. Is the rendered name the same you posted here?

**Comment by roederb** [comment]
Hi there,
yes it's actually the same name, i'm not sure why it's not working either. if i skip the <div> tag it works. no clou why. perhaps because in my case the <input> tag is one level down?

**Comment by johannesjo** [comment]
Which browser are you running, if I may ask?

**Comment by roederb** [comment]
Hi, i run on Firefox version38

Von: Johannes Millan [mailto:notifications@github.com]
Gesendet: Mittwoch, 17. Juni 2015 20:37
An: johannesjo/ng-fab-form
Cc: B. Roeder
Betreff: Re: [ng-fab-form] Asterisk for required label and bootstrap 3 (#75)


Which browser are you running, if I may ask?

**Comment by johannesjo** [comment]
Have you found a solution? Sorry for not evaluating this further. I close the ticket for now, but if the issue still persists, feel free to reopen.
