### ISSUE TITLE
npm version for webpack

### ISSUE THREAD

**Issue by atgillette** [johannesjo/ng-fab-form#78]
Hi,

I'm trying to use this library in conjunction with webpack.  But because this is a bower component, I've been unsuccessful get my angular to initialize properly.

I'm requesting an npm version of your library.

**Comment by johannesjo** [comment]
Hi there. I published a version to npm. Not sure how well it works out though, maybe you could check it out?

**Comment by atgillette** [comment]
Hi @johannesjo,

I just tried npm install ng-fab-form and got a message that it's not listed in the npm registry.

Adrian

**Comment by atgillette** [comment]
I just search on npm registry and it looks that it's listed as ng-fab-forms

**Comment by atgillette** [comment]
The npm version is working for me.  I had to require ng-messages in order to use ng-fab-form:

```
require('angular-messages');
require('ng-fab-forms');
```
