### ISSUE TITLE
Angular 1.4 compatibility

### ISSUE THREAD

**Issue by emasch** [johannesjo/ng-fab-form#80]
I've done an update to angular 1.4.3 but it seems not to work with ng-fab-forms 1.2.11.

The problem is, that I can't submit my form (i've checked, that it is valid. I also have removed all validators including required), but nothing happens. I've put a breakpoint in ng-fab-form.js and it was called, but it doesn't go on to the submit method, which is specified at the form element via ng-submit=""

Then I excluded ng-fab-forms and I can submit my forms, so it seems to be the plugin.

Please help.

**Comment by johannesjo** [comment]
Thanks for reporting. I'll look into this once I'm back from vacation.

**Comment by emasch** [comment]
I've testet a little bit and found out, that the error appears the first time, if I change the version from 1.2.9 to 1.2.10. But from the diff, it seems that it was mostly refactoring so I can't not really say why there's a problem.

But first, have a great vacation, and then look at this problem...

**Comment by johannesjo** [comment]
Hey there! Thanks. Was really fun :)

I looked into the problem, but I'm unable to reproduce the issue with angular#1.4.3. In my experience bower messes up from time to time if there are still files in a folder. Have you tried deleting the whole bower_components folder and installing everything again via bower install?

**Comment by przem** [comment]
We have the same problem with angular 1.4.7.
I've checked several times the delete/reinstall solution without luck.
According to bower.js it should work, there is a "angular": "~1.3"
But package.json has "angular": "~1.3.4". It should'nt  be used by bower install but well, that's the only spot that i've found. I'm not an expert in this matter so just guessing...

**Comment by johannesjo** [comment]
@przem  I just checked again and having no problems whatsoever. What other components are you using?

**Comment by przem** [comment]
@johannesjo that is really strange, i've removed all other components, added only fab-form and it worked, then added removed components and all still works...
Anyways, thanks for the hint

**Comment by johannesjo** [comment]
That's weird. Did you delete the whole bower_components folder before? Or did you change the load order in some way?
