### ISSUE TITLE
outdated validation-errors-template in demo breaks some style behaviors 

### ISSUE THREAD

**Issue by trophygeek** [johannesjo/ng-fab-form#82]
Might want to sync up after-submit.html in demos with the release default-validation-msgs.html
demo:
  https://github.com/johannesjo/ng-fab-form/blob/master/example/validation-examples/after-submit.html
release:
  https://github.com/johannesjo/ng-fab-form/blob/master/src/templates/default-validation-msgs.html
(diff the files)

Plunker demo of issue
http://plnkr.co/edit/iGX5VezNcPDuG7HVrvMi

See instructions in Plunker's app.js, but basically swap the production default-validation-msgs.html for demo's version after-submit.html. Then enter some invalid text in a field in the running example.

Demos are meant for new users and it's confusing when this file breaks the layout in a subtle way.

**Comment by johannesjo** [comment]
Thank you very much for reporting. You're absolutely right. I'll try to look into this once I've got a little more time on my hands.

**Comment by johannesjo** [comment]
I updated the template, but the reason why the plunker isn't working is actually a typo. The template your assigning is called after-sumbit.html while it should be after-submit.html.
