### ISSUE TITLE
on reset input fields still remain dirty

### ISSUE THREAD

**Issue by tushariscoolster** [johannesjo/ng-fab-form#84]
http://plnkr.co/edit/xJr2GHSeLG42W2qNH6KC?p=preview

after reset i can still see error message

**Comment by johannesjo** [comment]
That's because on submit the first missing required input gets focused. You can deactivate this behaviour, if you dont like it.

http://plnkr.co/edit/Bs7o48uxbYJ5AY9iWUaO?p=preview

**Comment by tushariscoolster** [comment]
:+1:  tnx
