### ISSUE TITLE
Fire validation mechanism for single input

### ISSUE THREAD

**Issue by circinus** [johannesjo/ng-fab-form#85]
Hi
First of all sorry for my English
I wonder if there is a possibility of firing mechanisms validation on a particular input from a controller.
This is because I have a form in two steps and I need to validate and show the errors of the fields in the first step
I understand that currently validations occur in the submit, but in my case the submit occurs in the second step

Thanks

**Comment by johannesjo** [comment]
Do understand you correctly and you're talking about a form split on two pages? You could always do:
```html
<form>
<div ng-show="formStep===1"><button type="button" click="formStep=2">bla</button></div>

<div ng-show="formStep===2">...
<button type="submit">Submit<button>
</div>
</form>
```
It's a little bit more complicated than that, but I'm sure you will figure it out. You might also want to try using ng-form, which should be supported by ng-fab-form.

From a usability perspective I would recommend to do the validation on the first step right away. It feels stupid to be thrown back to a previous step after I completed the second.

**Comment by circinus** [comment]
Right. I meant a form split on two pages
Use ng-form and worked well except for the fact that no error messages displayed in the inputs they had failed
To display these messages had to set on controller as $touched=true those inputs on

Thanks for the help!!

**Comment by johannesjo** [comment]
You're welcome :)
