### ISSUE TITLE
Chrome browser crashes when opening a page that contains a <form>

### ISSUE THREAD

**Issue by lhmiranda** [johannesjo/ng-fab-form#87]
When testing locally, everything works flawlessly. When I deploy to my S3 bucket and open the page, the browser hangs the moment I open a page that contains a form tag.

No error appears in console until it crashes.

Any idea of what could cause it?

**Comment by johannesjo** [comment]
Which version of ng-fab-form are you using?

**Comment by lhmiranda** [comment]
The latest one, v1.2.18.

**Comment by johannesjo** [comment]
Thanks for getting back to me. Are you deploying the files minified? That's really . Could you provide a link for further debugging? It should not matter where the files are deployed only how they look like..

**Comment by johannesjo** [comment]
Also: Does the same happen to you on the demo page or with the plunkr? They're using the minified version of this repo.

**Comment by lhmiranda** [comment]
Hey, sorry for the delay.
It was concatenated with other scripts and minified by a gulp task using gulp-uglify but I somehow fixed the issue by removing and readding the package via bower. 
I can try to get to the buggy revision in my repository to try and reproduce the problem if you still want to investigate the issue, tho.

**Comment by johannesjo** [comment]
Thank you very much for your reply. I'm glad that you were able to fix the problem. Bower does not always install the latest version if not explicitly told to do so, but might do it, when there is no package installed at all. That's probably the reason for your problem, as there was a bug in a later version of ng-fab-form, which caused the behavior you described.

**Comment by lhmiranda** [comment]
Oh, I see. That's probably what happened. Well, thanks for your time and for the awesome work on this package! Thanks a lot!
