### ISSUE TITLE
Execute function before focusing on first erroneous input

### ISSUE THREAD

**Issue by juliancho1025** [johannesjo/ng-fab-form#89]
it would be very useful to be able to execute some actions before focusing in the first error. 
Like showing a message to the user.
Or adding a message for Screen Reader users (to be compatible with WCAG)

**Comment by johannesjo** [comment]
I don't know if this is helpful for you, but you can specify a custom scroll to function.

**Comment by juliancho1025** [comment]
you are right, I didn't see that option
