### ISSUE TITLE
Validation trigger on ng-click instead of submit

### ISSUE THREAD

**Issue by baskaranr** [johannesjo/ng-fab-form#91]
Hi,

I have two actions in my form "save", "save and approve". 
So i want to trigger validation manually in both actions instead of form-submit.
Please do the needful.

Thanks,
Baskar

**Comment by johannesjo** [comment]
You can use `<button type="button"></button>` together with this approach to manually trigger a form submit:
http://stackoverflow.com/questions/16003188/can-i-trigger-a-form-submit-from-a-controller

**Comment by baskaranr** [comment]
Thanks for the quick reply.
I tried the solutions mentioned in the stackoverflow link.
But those solutions doesn't trigger fab-form validations.

**Comment by johannesjo** [comment]
If you trigger the submit, the validation is triggered, isn't it?

**Comment by baskaranr** [comment]
yes. but its not working while invoke submit from controller code as mentioned in stackoverflow answers.

**Comment by johannesjo** [comment]
Oh that's interesting! I'll have to check this you
Out. Could you by any chance provide a plunkr?

**Comment by baskaranr** [comment]
Sorry. I have been using this plugin part of project and couldn't able to
extract the form code in plunkr

**Comment by johannesjo** [comment]
Hey there. I checked again. To trigger the validation messages (at least with the default validations-tempalte) you can set form controllers `$triedSubmit` property to true. Here is an example:
http://plnkr.co/edit/jIGCxuXGIPkB60ZJP0jS?p=preview

**Comment by baskaranr** [comment]
Hi,

Thanks for the plnkr.
Its very closer to my requirement.
The submit doesn't call the respective method if validation fails. 
In triedsubmit case we have to handle it as like fake submit - 2.

Please check the modified plunkr.
http://plnkr.co/edit/qlOgr6n6NPtujff8Wzg8?p=preview

**Comment by johannesjo** [comment]
Sorry, Im not sure what the issue is. can you elaborate further? 
`if(!form.$valid) { return;}` does not solve your problem?

**Comment by baskaranr** [comment]
It solves the problem. but submit button click its handled without this code block.

**Comment by johannesjo** [comment]
Sorry, you have to explain a little better what the problem is, you're facing.

**Comment by baskaranr** [comment]
sorry, it works as expected.
Please go through this fiddle for reference. [Fake submit 1 click and Fake submit 2 click]

http://plnkr.co/edit/qlOgr6n6NPtujff8Wzg8?p=preview

**Comment by johannesjo** [comment]
I'm glad, that it works!
